#pipeline TP3

trigger:
  branches:
    include:
      - main  # Déclenche uniquement sur la branche principale

variables:
  serviceConnection : 'SC-TP3'
  resourceGroupName: 'rg-tp3-devops'
  location: 'canadacentral'
  templateFile: './main.bicep'
  webAppName: 'webapp-tp3'
  webAppNameProd : 'webapp-tp3'
  sqlServerName : 'tp3-sql'
  sqlAdminLogin : 'tp3-admin'
  sku: 'TP3'
  
stages:
  - stage: Deploy_Dev
    displayName: Deploy to Dev Environment
    jobs:
      - job: DeployToDev
        displayName: Deploy Resources to Dev
        pool:
          vmImage: 'windows-latest'  # Utilise une machine virtuelle Windows
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(serviceConnection)  # Nom de votre service Azure connecté
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                  az --version
                  az group create --name $(resourceGroupName) --location $(location)
                  az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters location=$(location) sqlServerName=$(sqlServerName) sqlAdminLogin=$(sqlAdminLogin) sqlAdminPassword=$(sqlAdminPassword)

                  param location string


  - stage: Deploy_Production
    displayName: Deploy to Production Environment
    dependsOn: Deploy_Dev
    condition: succeeded()
    jobs:
      - deployment: DeployToProd
        displayName: Deploy Resources to Production
        pool:
          vmImage: 'windows-latest'  # Utilise une machine virtuelle Windows
        environment: 'Production'  # Environnement Azure Pipelines
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: $(serviceConnection)  # Nom de votre service Azure connecté
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                        az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters appName=$(webAppNameProd) appSku=$(sku)










